[package]
name = "rust-scroller"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.12.0"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }

[features]
# empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
# vulkan = ["amethyst/vulkan"]
