[package]
name = "rust-scroller"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
amethyst = "0.12.0"
specs-physics = { version = "0.3.0", features = ["amethyst"] }

[features]
# empty = ["amethyst/empty"]
metal = ["amethyst/metal"]
# vulkan = ["amethyst/vulkan"]
